### ISSUE TITLE
[1.10.2] game crash with new versions: java.lang.NoClassDefFoundError: sonar/calculator/mod/api/machines/ICalculatorGenerator

### ISSUE THREAD

**Issue by Protheus** [SonarSonic/Practical-Logistics#108]
**What happens:**
Game crash when loading it up with the new 1.10.2 version of practical logistics

**Versions:**
MC: 1.10.2
Forge: 2202
PracticalLogistics-1.10.2-2.0.0
SonarCore-1.10.2-3.2.2

Calculator-1.10.2-3.1.6

**What should happen:**
Game should load without crashing on sonar core/calculator mod

**Pastebin**: 
http://pastebin.com/YdSRYruN

**Reproduce:**
1. add the above versions of the mods to your setup
2. load minecraft
3. will give a crash log in console after 30s (depending on system ofcourse)

**Short:**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
  RebornCoreASM (RebornCore-1.10.2-2.12.1.96-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.1.0.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 13/01/17 09:03
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Practical Logistics (practicallogistics)
Caused by: java.lang.NoClassDefFoundError: sonar/calculator/mod/api/machines/ICalculatorGenerator
	at sonar.logistics.info.registries.CalculatorInfoRegistry.registerBaseMethods(CalculatorInfoRegistry.java:29)
	at sonar.logistics.info.LogicInfoRegistry.lambda$init$1(LogicInfoRegistry.java:97)
	at java.util.ArrayList.forEach(Unknown Source)
	at sonar.logistics.info.LogicInfoRegistry.init(LogicInfoRegistry.java:97)
	at sonar.logistics.Logistics.preInit(Logistics.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: sonar.calculator.mod.api.machines.ICalculatorGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException

**Comment by SonarSonic** [comment]
Thanks for reporting, this is my fault, haven't updated calculator since developing on it. I'll put a new 1.10.2 Practical Logistics up.
