### ISSUE TITLE
BUG - Server Crash with Info Reader

### ISSUE THREAD

**Issue by Utildayael** [SonarSonic/Practical-Logistics#83]
I got a bad one for you. In our case, the world was corrupted after that crash and we had to restore from backup. That part however I wasn't able to reproduce in my SP world as it was still ok after crash. 

**Practical-Logistics-1.7.10-0.2.4**

We had this on our MP server and I was able to recreate it in an SP world as well. Very easy to repro.

1. Place Rotarycraft extractor
2. Place an InfoReader on extractor
3. Right-click the InfoReader to open GUI
4. Crash to desktop :(

I put my crash log in a pastebin, see below. Here's the short snippet of it:

```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: sonar.core.helpers.NBTHelper$SyncType.isType([Lsonar/core/helpers/NBTHelper$SyncType;)Z
	at sonar.logistics.helpers.InfoHelper.writeInfoToNBT(InfoHelper.java:174)
	at sonar.logistics.common.handlers.InfoReaderHandler.writeData(InfoReaderHandler.java:176)
	at sonar.core.common.tileentity.TileEntityHandler.writeData(TileEntityHandler.java:25)
	at sonar.core.common.tileentity.TileEntitySonar.sendSyncPacket(TileEntitySonar.java:111)
	at sonar.logistics.common.blocks.BaseNode.operateBlock(BaseNode.java:61)
	at sonar.core.common.block.SonarBlock.func_149727_a(SonarBlock.java:76)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

```

http://pastebin.com/yCg8GJed

**Comment by Utildayael** [comment]
Exact same issue if I attach to a Thermal Expansion machine fwiw.

**Comment by SonarSonic** [comment]
Update SonarCore

**Comment by Utildayael** [comment]
Will do. Thanks for the quick reply! Hadn't realize we were behind a version. :)
